name: release
on:
  push:
    tags:
      - 'v*'
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux, windows, macos]
        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/glrun
            asset_name: glrun-linux
          - name: windows
            os: windows-latest
            artifact_name: target/release/glrun.exe
            asset_name: glrun-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/glrun
            asset_name: glrun-macos

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build
      run: cargo build --release --locked

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref }}
        files: ${{ matrix.artifact_name }}/${{ matrix.asset_name }}
        token: ${{ secrets.USER_TOKEN }}
